repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: "^.vscode/"
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c 'black --check .'
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: bash -c 'pflake8 --exclude=./containers/fastapi/src/gunicorn.conf.py ./containers/fastapi/src'
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: bash -c 'isort -c .'
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
