version: '3.9'
services:
  app:
    build:
      target: prod
    volumes:
      - ./containers :/ailab_line/containers
    ports:
      - ${PROD_APP_PORT}:${PROD_APP_PORT}
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=${PROD_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PROD_MYSQL_DATABASE}
      - MYSQL_USER=${PROD_MYSQL_USER}
      - MYSQL_PASSWORD=${PROD_MYSQL_PASSWORD}
      - PORT=${PROD_APP_PORT}
    ports:
      - "13306:${PROD_DB_PORT}"
