version: '3.9'
services:
  app:
    container_name: app_container
    working_dir: /poetry_practice
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/poetry_practice
    environment:
      TZ: Asia/Tokyo
    tty: true
